### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by cansubmarinesswim** [I-Behdar/Weather_Forcast#1]
Currently there is no pull request for me to create comments under. For future project development - please create relevant branches / create relevant pull requests.

## Repository related
1. Your `README.md` suggests that running `setup.py` after `setup.sh` is required, but this is not the case - `setup.sh` is enough.
2. `requests` is not a part of python standard library. Your project requires them, but they are not included in `requirements.txt`/`install_requires`.

## Code related
1. Please, add if [__name__=='__main__':](https://stackoverflow.com/questions/419163/what-does-if-name-main-do). Inside main function you could parse args and fetch the weather data.
2. Consider adding exceptions handling, for example - each returned json contains `STATUS` key. It might be a good place to start
For failed request (bad city name provided)
```python
...
        "STATUS": {
            "access": "FREE_USER, ACCESS_GRANTED",
            "status": "FAILED, NO_RESULTS"
...
```

for successfull request
```
        "STATUS": {
            "access": "FREE_USER, ACCESS_GRANTED",
            "status": "SUCCESS",
            "address_provided": "kraków",
            "result_count": 1
        },
```
3. Function name `coordinates` is not a great one. Consider something more specific like `get_city_coordinates`
4. The current handling of responses from api is not well readable. Consider creating helper functions that takes the response and extracts the information into some dictionary, that is later used by other functions.
When you incorporate this kind of "mapping" the app itself becomes more modular - if weather api decides to change the structure of the response, you only have to worry about changing the helper function, because the rest of the app uses values returned from this function and not the response itself.

**Comment by I-Behdar** [comment]
> 4. The current handling of responses from api is not well readable. Consider creating helper functions that takes the response and extracts the information into some dictionary, that is later used by other functions.
>    When you incorporate this kind of "mapping" the app itself becomes more modular - if weather api decides to change the structure of the response, you only have to worry about changing the helper function, because the rest of the app uses values returned from this function and not the response itself.


All the parts are done except Code #4 as I don't understand what to do, isn't the api itself a dictionary? I think I already have helper functions, don't I?

**Comment by mstopa** [comment]
Closing this as we have now a PR for the following discussion: https://github.com/I-Behdar/Weather_Forcast/pull/2
